In [1]:
import ssid
import scipy
import numpy as np

In [2]:
impulse_series = scipy.io.loadmat("Uploads/impulse_series.mat")

In [3]:
output = impulse_series["y1"]
t = impulse_series["times"]
output = np.array([output.T])
output

array([[[ 7.40880024e-07,  4.15541551e-06,  2.77047390e-06,
          7.74192252e-07,  5.27263954e-07,  7.25116016e-07,
          1.63176569e-06, -1.53364704e-06, -5.42891090e-06,
         -2.92401259e-06,  9.48826018e-07,  1.58668383e-06,
          1.34608611e-06,  3.83663044e-07,  1.47727941e-06,
          4.17081458e-06,  1.43019315e-06, -3.43795382e-06,
         -3.58854068e-06, -1.84718246e-06, -2.01891329e-07,
          2.85159923e-07, -1.44407616e-06,  2.30912834e-07,
          4.59231461e-06,  3.88458616e-06,  2.59103979e-07,
         -1.80523417e-06, -2.37273309e-06, -6.46495988e-07,
         -4.32616045e-07, -3.39404096e-06, -2.39042584e-06,
          2.14743804e-06,  3.83174545e-06,  3.00131423e-06,
          5.93654418e-07, -1.13843116e-06,  6.92519288e-07,
          5.71128043e-07, -3.35612721e-06, -4.19201880e-06,
         -1.56026914e-06,  1.34288832e-06,  3.18178696e-06,
          1.46136386e-06, -1.28224439e-07,  2.27013894e-06,
          2.68650390e-06, -7.96118914e-0

In [5]:
A,B,C,D = ssid.realize.era(output, r=6, svd={"full_matrices": False})

In [6]:
A

array([[ 8.32257341e-01, -5.52267593e-01, -3.21157678e-03,
         3.73577377e-03,  1.88885612e-03,  3.24397162e-04],
       [ 5.52267593e-01,  8.33940465e-01, -6.27948139e-03,
        -2.14266322e-03,  3.17867401e-03,  1.67675329e-03],
       [-3.21157678e-03,  6.27948139e-03,  2.28567441e-01,
         9.70939275e-01,  1.12046468e-03, -9.97116724e-04],
       [-3.73577377e-03, -2.14266322e-03, -9.70939275e-01,
         2.29602498e-01, -6.62404933e-03, -2.61335574e-03],
       [ 1.88885612e-03, -3.17867401e-03,  1.12046468e-03,
         6.62404933e-03, -5.46426695e-01,  8.30213517e-01],
       [-3.24397162e-04,  1.67675329e-03,  9.97116724e-04,
        -2.61335574e-03, -8.30213517e-01, -5.46408139e-01]])

In [7]:
B

array([[-0.00140695],
       [ 0.00075015],
       [-0.00151307],
       [-0.00018132],
       [ 0.00081754],
       [-0.00023729]])

In [8]:
C

array([[-0.00140695, -0.00075015, -0.00151307,  0.00018132,  0.00081754,
         0.00023729]])

In [9]:
D

array([[7.40880024e-07]])

In [10]:
from ssid import modal
modal.system_modes((A,B,C,D), t[1]-t[0])

{'1': {'freq': 372.6806911664372,
  'damp': 0.0007802493556840395,
  'modeshape': array([-0.00099015-0.00053289j]),
  'cnd': 1.0000113409255906,
  'energy_condensed_emaco': 0.9999999999999722,
  'mpc': 1.0},
 '3': {'freq': 852.5057724678616,
  'damp': 0.0017832802252856549,
  'modeshape': array([0.00107319+0.00012562j]),
  'cnd': 1.000034225132876,
  'energy_condensed_emaco': 0.9999999999998763,
  'mpc': 1.0},
 '5': {'freq': 1370.570222186297,
  'damp': 0.0028409031574394457,
  'modeshape': array([-0.00058211+0.00017423j]),
  'cnd': 1.000030160170077,
  'energy_condensed_emaco': 0.9999999999999837,
  'mpc': 1.0}}