In [1]:
import quakeio
import ssid

from pathlib import Path
import numpy as np
import pandas as pd

In [2]:
# channels = ["22", "24"]
# channels = ["23", "25"]
channels = dict( # PAINTER RIO DELL
    inputs  = [17, 3, 20],
    outputs = [ 9, 7 , 4]
)
# channels = dict(# Case 2
#     inputs  = [3,6,17],
#     outputs = [12, 14, 19]
# )
# channels = dict( # Case 5
#     inputs  = [1],
#     outputs = [16]
# )
# channels = dict(
#     inputs  = "2 7 25".split(),
#     outputs = "18 13 15 23 20".split()
# )

In [8]:
for file in Path("/mnt/d/CSMIP/painter").glob("*.zip"):
    event = quakeio.read(file)
    print(f"{file.name}")
    try:
        inputs = [
            event.match("r", file_name=f".*{chan}.*").accel
            for chan in channels["inputs"]
        ]
        outpts = [
            event.match("r", file_name=f".*{chan}.*").accel
            for chan in channels["outputs"]
        ]
        dt = inputs[0]["time_step"]
        V = ssid.okid_era_dc(inputs, outpts, dt=dt, kmax=500, mro=10, orm=4, verbose=True)
    except:
        print(f"\tFAILED")
        
    else:
        print(ssid.IdentifiedSystem(dt, **V))
        # break

        # A,B,C,D = OKID.okid(inputs, outpts, dt=dt, kmax=500, mro=10, orm=4, verbose=True)
        # freqdmpSRIM, modeshapeSRIM, *_ = si.ComposeModes(dt, A, B, C, D)
        # Add validation
        # print(si.IdentifiedSystem(dt, A, B, C, D))
        # print(file, np.real(1/freqdmpSRIM[:,0]))

CapeMendocino_21Nov1986_CE89324P.zip
	FAILED
petrolia_05dec2016_72733405_ce89324p.zip

Spectral quantities:
       T      𝑓       ζ
    0.2353  4.25    0.02229
    0.02182  45.83   0.07042

RioDell82_CE89324P.zip
	FAILED
CapeMendocino_31Jul1987_CE89324P.zip

Spectral quantities:
       T      𝑓       ζ
    0.2351  4.254   0.02096
    0.2012  4.97    0.05834

nc73201181_ce89324p.zip
Error extracting modes: too many indices for array: array is 1-dimensional, but 2 were indexed
RioDell_Petrolia_Processed_Data.zip

Spectral quantities:
       T      𝑓       ζ
    0.2314  4.321   0.0435
    0.1773  5.64    0.05128

riodell_14sep2012_71842075_ce89324p.zip

Spectral quantities:
       T      𝑓       ζ
    0.2401  4.165   0.09522
    0.1309  7.637   0.1544

ferndale_28jan2015_72387946_ce89324p.zip

Spectral quantities:
       T      𝑓       ζ
    0.1774  5.638   0.005023
    0.02393  41.79   0.04323

PetroliaAftershock1_26Apr1992_CE89324P.zip
	FAILED
Eureka_24Aug1983_CE89324P.zip
	FAILED
Trini

In [4]:
syst = ssid.IdentifiedSystem(dt, **V)
syst.freqdmp

array([[4.18186327e+00+0.j, 5.17009197e-02+0.j, 3.13693463e+15+0.j],
       [5.72718333e+00+0.j, 1.51164858e-01+0.j, 3.11951521e+15+0.j]])

In [5]:
ssid.condeig(V["A"])

(array([[ 0.00306648-6.93610200e-01j,  0.00306648+6.93610200e-01j,
         -0.03848267+2.03315313e-02j, -0.03848267-2.03315313e-02j],
        [ 0.69411933+0.00000000e+00j,  0.69411933-0.00000000e+00j,
         -0.02002728-3.59662593e-02j, -0.02002728+3.59662593e-02j],
        [ 0.01545057-1.48711433e-01j,  0.01545057+1.48711433e-01j,
          0.72228294+0.00000000e+00j,  0.72228294-0.00000000e+00j],
        [-0.12140805+3.47114989e-04j, -0.12140805-3.47114989e-04j,
          0.02437008-6.88566994e-01j,  0.02437008+6.88566994e-01j]]),
 array([0.98469431+0.12993972j, 0.98469431-0.12993972j,
        0.95781657+0.17217386j, 0.95781657-0.17217386j]),
 array([3.13693463e+15, 3.13693463e+15, 3.11951521e+15, 3.11951521e+15]))

In [6]:
def hankel(Y, d, shift):
    from numpy.lib.stride_tricks import as_strided
    if shift:
        Y = np.roll(Y,1)
    return as_strided()
    return np.lib.stride_tricks.sliding_window_view(
            Y, (Y.shape[0], Y.shape[1]+1-d)
    ).reshape(d*Y.shape[0], -1)

In [7]:
hankel(np.array(V["Y"]), 10, 0)

TypeError: as_strided() missing 1 required positional argument: 'x'

In [ ]:
np.array(V["dati"]).shape

In [ ]:
print(si.IdentifiedSystem(dt, -V["A"]))