In [1]:
import quakeio
import ssid

from pathlib import Path
import numpy as np
import pandas as pd

In [2]:
# channels = ["22", "24"]
# channels = ["23", "25"]
channels = dict( # PAINTER RIO DELL
    inputs  = [17, 3, 20],
    outputs = [ 9, 7 , 4]
)
# channels = dict(# Case 2
#     inputs  = [3,6,17],
#     outputs = [12, 14, 19]
# )
# channels = dict( # Case 5
#     inputs  = [1],
#     outputs = [16]
# )
# channels = dict(
#     inputs  = "2 7 25".split(),
#     outputs = "18 13 15 23 20".split()
# )

In [3]:
for file in Path("painter").glob("RioDell_P*.zip"):
    event = quakeio.read(file)
    try:
        inputs = [
            event.match("r", file_name=f".*{chan}.*").accel
            for chan in channels["inputs"]
        ]
        outpts = [
            event.match("r", file_name=f".*{chan}.*").accel
            for chan in channels["outputs"]
        ]
    except:
        print(f"failed {file.name}")
        
    else:
        dt = inputs[0]["time_step"]
        V = ssid.okid_era_dc(inputs, outpts, dt=dt, kmax=500, mro=10, orm=4, verbose=True)
        print(ssid.IdentifiedSystem(dt, **V))
        # break

        # A,B,C,D = OKID.okid(inputs, outpts, dt=dt, kmax=500, mro=10, orm=4, verbose=True)
        # freqdmpSRIM, modeshapeSRIM, *_ = si.ComposeModes(dt, A, B, C, D)
        # Add validation
        # print(si.IdentifiedSystem(dt, A, B, C, D))
        # print(file, np.real(1/freqdmpSRIM[:,0]))


Spectral quantities:
       T      𝑓       ζ
    0.03683  27.15   0.0435
    0.02822  35.44   0.05128



In [4]:
syst = ssid.IdentifiedSystem(dt, **V)
syst.freqdmp

array([[2.71481609e+01+0.j, 4.35022318e-02+0.j, 3.07664596e+15+0.j],
       [3.54367861e+01+0.j, 5.12769675e-02+0.j, 1.21034958e+15+0.j]])

In [5]:
ssid.condeig(V["A"])

(array([[ 0.00485692-0.69467824j,  0.00485692+0.69467824j,
          0.07499374+0.05789865j,  0.07499374-0.05789865j],
        [ 0.69560738+0.j        ,  0.69560738-0.j        ,
         -0.06211211+0.06222664j, -0.06211211-0.06222664j],
        [-0.04893069-0.11973605j, -0.04893069+0.11973605j,
         -0.70676765+0.j        , -0.70676765-0.j        ],
        [-0.11470251+0.06034349j, -0.11470251-0.06034349j,
         -0.00337645+0.69552981j, -0.00337645-0.69552981j]]),
 array([0.95213214+0.26476604j, 0.95213214-0.26476604j,
        0.9211368 +0.34031987j, 0.9211368 -0.34031987j]),
 array([3.07664596e+15, 3.07664596e+15, 1.21034958e+15, 1.21034958e+15]))

In [6]:
pd.DataFrame(V["R1"])

0         1         2         3         4         5         6     \
0    -0.080028  0.054956  0.112426  0.087229  0.103388 -0.328922 -0.602950   
1    -0.147761  0.108918  0.047327  0.084324  0.027890  0.147629  0.045567   
2    -0.066649  0.028279 -0.165355 -0.094606 -0.530942  0.103629  0.063879   
3    -0.093693  0.025736  0.129400  0.033496  0.146005 -0.402209  0.222534   
4    -0.168731  0.062281  0.070972  0.056507  0.001109  0.167589 -0.040009   
...        ...       ...       ...       ...       ...       ...       ...   
1495  0.000535 -0.000170  0.000131 -0.000080 -0.000044 -0.000070  0.000009   
1496  0.000230 -0.000099  0.000019  0.000022 -0.000030 -0.000016  0.000003   
1497  0.000240  0.000021  0.000060 -0.000078 -0.000004 -0.000036  0.000005   
1498  0.000552 -0.000013  0.000103 -0.000108 -0.000026 -0.000066  0.000010   
1499  0.000244 -0.000030  0.000028  0.000018 -0.000032 -0.000021  0.000006   

          7         8             9     ...      1490      1491      1492  \
0     0.306923  0.058445  3.164893e-01  ... -0.000207  0.000033 -0.000205   
1    -0.054910  0.078111  3.815578e-02  ... -0.000118  0.000015 -0.000018   
2     0.365981 -0.069071  2.458947e-01  ...  0.000027 -0.000062  0.000042   
3    -0.209266 -0.519686  3.069223e-01  ...  0.000280 -0.000098  0.000175   
4    -0.114557 -0.029772 -6.785092e-02  ...  0.000168 -0.000016 -0.000165   
...        ...       ...           ...  ...       ...       ...       ...   
1495  0.000009  0.000029  2.100500e-06  ...  0.022861  0.051148  0.018049   
1496  0.000008 -0.000002  5.583726e-06  ...  0.275336  0.034878 -0.069381   
1497  0.000002  0.000017  2.461499e-08  ...  0.116866  0.019856 -0.017881   
1498  0.000010  0.000025  4.680911e-06  ... -0.004048 -0.025245 -0.003191   
1499  0.000007  0.000003  2.467660e-06  ... -0.264368 -0.047350  0.038571   

          1493      1494      1495          1496      1497      1498      1499  
0     0.000080 -0.000039  0.000125  5.119544e-05  0.000184 -0.000094  0.000092  
1    -0.000024 -0.000116  0.000024 -1.200326e-05  0.000007  0.000049  0.000024  
2     0.000008  0.000060 -0.000091  1.897956e-05 -0.000014 -0.000009  0.000012  
3    -0.000158  0.000064 -0.000175  8.758579e-07 -0.000180  0.000044 -0.000128  
4     0.000123  0.000282  0.000034  8.589602e-05  0.000159 -0.000212 -0.000006  
...        ...       ...       ...           ...       ...       ...       ...  
1495  0.009248 -0.007820  0.036354  4.010294e-02  0.075671  0.007469  0.009467  
1496 -0.105579 -0.056102 -0.137262  9.514402e-02  0.003038  0.194470 -0.069581  
1497 -0.017724 -0.127393  0.071027 -9.539234e-02  0.112933  0.235331 -0.010351  
1498 -0.013518  0.001043 -0.011540 -1.210028e-02 -0.028579  0.008190 -0.012364  
1499  0.040074 -0.020213  0.014983 -7.513423e-02 -0.038465 -0.078962  0.038909  

[1500 rows x 1500 columns]

In [7]:
[y[0] for y in V["Y"][-13:]]

[array([ 1.69532602e-38, -5.96983665e-38, -9.26902802e-38]),
 array([ 4.49510895e-38,  4.61057771e-38, -6.49897388e-38]),
 array([ 6.90410705e-38,  1.46143917e-37, -3.31939343e-38]),
 array([8.75601736e-38, 2.33271451e-37, 2.91145522e-40]),
 array([9.92884772e-38, 3.01445722e-37, 3.29915088e-38]),
 array([1.03527793e-37, 3.46140385e-37, 6.25466515e-38]),
 array([1.00140549e-37, 3.64640054e-37, 8.68786564e-38]),
 array([8.95470136e-38, 3.56196499e-37, 1.04336882e-37]),
 array([7.26820086e-38, 3.22038218e-37, 1.13808278e-37]),
 array([5.09151817e-38, 2.65236003e-37, 1.14786080e-37]),
 array([2.59414742e-38, 1.90437590e-37, 1.07392842e-37]),
 array([-3.49575323e-40,  1.03493654e-37,  9.23571781e-38]),
 array([-2.60156997e-38,  1.10048387e-38,  7.09469438e-38])]

In [8]:
def hankel(Y, d, shift):
    from numpy.lib.stride_tricks import as_strided
    if shift:
        Y = np.roll(Y,1)
    return as_strided()
    return np.lib.stride_tricks.sliding_window_view(
            Y, (Y.shape[0], Y.shape[1]+1-d)
    ).reshape(d*Y.shape[0], -1)

In [9]:
hankel(np.array(V["Y"]), 10, 0)

TypeError: as_strided() missing 1 required positional argument: 'x'

In [ ]:
np.array(V["dati"]).shape

In [ ]:
print(si.IdentifiedSystem(dt, -V["A"]))